### ISSUE TITLE
A handmade theme may be ok for this project

### ISSUE THREAD

**Issue by meisheep** [jserv/facebooc#19]
Hi, I'm developing a handmade theme having no dependency (no Bootstrap or jQuery).

The only 3rd party lib I use is `Normalize.css`, which is to prevent the incoherence between different browsers. It can be removed if a few incoherence is tolerable.

The following images are the pages preview what I've done:

**Landing Page**
<img width="1280" alt="2016-05-12 4 35 19" src="https://cloud.githubusercontent.com/assets/8501092/15196056/36a3953e-17fd-11e6-8583-e73d7b3a3b29.png">

**Login Form**
<img width="1280" alt="2016-05-12 4 35 22" src="https://cloud.githubusercontent.com/assets/8501092/15196082/54a39480-17fd-11e6-94c2-f129bb59fd43.png">

**Sign Up Form**
<img width="1280" alt="2016-05-12 4 35 24" src="https://cloud.githubusercontent.com/assets/8501092/15196087/5895e70a-17fd-11e6-9c4d-81ab96311be5.png">

I don't know whether this theme can fit your requirements. If yes, I will keep on developing. Thanks.

**Comment by jserv** [comment]
@meisheep : The theme is wonderful. I like it. Please keep hacking.
