### ISSUE TITLE
segmentation error, for action post and for 64 bit only

### ISSUE THREAD

**Issue by chezsick** [jserv/facebooc#40]
each time to post thing, return a segmentation error in 64 bit, but for 32 bit is passed.

please fix this, Sick

**Comment by timp87** [comment]
That happens due to missing bsNewline2BR declaration in header file.
So without that compiler thinks bsNewline2BR returns an int by default.

The fix is easy.

```
diff --git a/include/bs.h b/include/bs.h
index a86c015..dbf1b85 100644
--- a/include/bs.h
+++ b/include/bs.h
@@ -14,6 +14,7 @@ char     *bsCat(char *, char *);
 char     *bsSubstr(char *, uint32_t, int32_t);
 char     *bsRandom(uint32_t, char *);
 char     *bsEscape(char *);
+char     *bsNewline2BR(char *);
 void      bsLCat(char **, char *);
 void      bsDel(char *);
 void      bsSetLen(char *, uint32_t);
```

**Comment by jserv** [comment]
Thank @timp87 for figuring out the problem. Merged in master branch.
