### ISSUE TITLE
bs.c 裡面的 bsNew, bsNewLen 等 function ，是不是應該要檢查 malloc 是否有成功？

### ISSUE THREAD

**Issue by WithGJR** [jserv/facebooc#7]
目前 bsNew, bsNewLen 等等 function 裡面並沒有針對 malloc 是否成功做檢查，是不是應該要檢查是否為 NULL 呢？還是之所以不檢查是因為有其他的原因？

因為我對C其實沒有很熟悉，想請教我的想法是否有誤。

另外，假設我的想法是對的話，以這幾個 function 來說，是不是直接用 assert 檢查就好了？

有必要加上檢查的話，我會再幫忙送 PR ，感謝

**Comment by jserv** [comment]
Use `assert()` for checking the results of memory allocations.

**Comment by WithGJR** [comment]
以bsNew來說，意思是把它改成這樣嗎？不知道我有沒有理解錯誤？

``` c
char *bsNew(const char *str)
{
    size_t len = strlen(str);
    char *bs = malloc(sizeof(char) * BS_HEADER_LEN +
                      sizeof(char) * (len + 1));
    assert(bs != NULL);
    bs += BS_HEADER_LEN;

    strcpy(bs, str);
    bsSetLen(bs, len);

    return bs;
}
```

**Comment by jserv** [comment]
At present, all `malloc()` calls are assumed a success while `assert()` is used for principle of least checking. You can write as following:

``` c
char *bs = malloc(sizeof(char) * (BS_HEADER_LEN + len + 1));
assert(bs);
```

**Comment by WithGJR** [comment]
剛剛提交PR了，再麻煩您看一下，謝謝
